/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "sanctum.csrf-cookie": [],
    "api.categories.show": [
        {
            "name": "projectId",
            "required": true
        },
        {
            "name": "categoryId",
            "required": true
        }
    ],
    "api.categories.update": [
        {
            "name": "projectId",
            "required": true
        },
        {
            "name": "categoryId",
            "required": true
        }
    ],
    "api.categories.reorder": [
        {
            "name": "project",
            "required": true
        },
        {
            "name": "category",
            "required": true
        }
    ],
    "api.tasks.reorder": [
        {
            "name": "projectId",
            "required": true
        },
        {
            "name": "categoryId",
            "required": true
        },
        {
            "name": "taskId",
            "required": true
        }
    ],
    "home": [],
    "register": [],
    "login": [],
    "project.create": [],
    "project.store": [],
    "task.create": [],
    "task.store": [],
    "task.destroy": [
        {
            "name": "id",
            "required": true
        }
    ],
    "task.update": [
        {
            "name": "id",
            "required": true
        }
    ],
    "dashboard.index": [
        {
            "name": "projectId",
            "required": true
        }
    ],
    "logout": [],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}
export {};
